Rebase Docker images to ubuntu:20.04  - WIP (#816)
* Rebase Docker images to ubuntu:20.04.

* Manually set ENV TZ in Dockerfile.jupyterlab.

Required for step installing jupyterlab:
RUN /opt/scripts/install-apt.sh /opt/jupyterlab/apt.txt

Set to CDT

* Have jovyan own home dir for testing.

Local testing running docker run -p 8888:8888 -it <image name> jupyter lab
--ip=0.0.0.0 returns:
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'

Changing ownership of /home/jovyan to user jovyan removes this error and
allows local testing of the container.